FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y default-jre-headless && \
    apt-get clean;

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app/src

CMD ["python", "src/streaming/spark_processor.py"]