FROM python:3.11-slim

WORKDIR /app

COPY src/serving/requirements.serving.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src/serving/ .

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]