FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install aiohttp minio kafka-python requests psycopg2-binary
CMD ["python", "/app/src/ingestion/main_polling.py"]
