apiVersion: 1

datasources:
  - name: PostgreSQL-Traffic
    type: postgres
    access: proxy
    isDefault: false
    editable: true
    url: postgres:5432
    user: traffic_user
    secureJsonData:
      password: traffic_pass
    jsonData:
      database: trafficdb
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
